// This file is auto-generated by @hey-api/openapi-ts

export type SignupAuthDto = {
  email: string;
  password: string;
  name: string;
};

export type LoginAuthDto = {
  email: string;
  password: string;
};

export type FindUserDto = {
  email: string;
};

export type ReturnUserDto = {
  _id: string;
  _email: string;
  _name?: string;
  _passwordHash: string;
};

export type CreateEventGroupDto = {
  title: string;
  currency?: {
    [key: string]: unknown;
  };
};

export type EventGroupDetailDto = {
  id: string;
  title: string;
  currency: string;
  createdAt: string;
  member: Array<{
    id: string;
    name: string;
  }>;
  expenses: Array<{
    id: string;
    title: string;
    payer: {
      id?: string;
      name?: string;
    };
    payees?: Array<{
      id: string;
    }>;
  }>;
  settlements: Array<{
    id: string;
    payeeId: string;
    payerId: string;
    amount: number;
  }>;
};

export type EventGroupDto = {
  id: string;
  title: string;
  memberCount: number;
  createdAt: string;
};

export type MemberDto = {
  memberId: string;
};

export type ExpenseDto = {
  title: string;
  amount: number;
  payerId: string;
  payeeIds: Array<string>;
};

export type SignupData = {
  body: SignupAuthDto;
  path?: never;
  query?: never;
  url: '/auth/signup';
};

export type SignupResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type LoginData = {
  body: LoginAuthDto;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type LoginResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type LogoutResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type RefreshResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type FindByEmailData = {
  body: FindUserDto;
  path?: never;
  query?: never;
  url: '/user';
};

export type FindByEmailResponses = {
  201: ReturnUserDto;
};

export type FindByEmailResponse =
  FindByEmailResponses[keyof FindByEmailResponses];

export type GetAllGroupsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/event-group';
};

export type GetAllGroupsResponses = {
  200: Array<EventGroupDto>;
};

export type GetAllGroupsResponse =
  GetAllGroupsResponses[keyof GetAllGroupsResponses];

export type CreateData = {
  body: CreateEventGroupDto;
  path?: never;
  query?: never;
  url: '/event-group';
};

export type CreateResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type DeleteGroupData = {
  body?: never;
  path: {
    groupId: string;
  };
  query?: never;
  url: '/event-group/{groupId}';
};

export type DeleteGroupResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type DeleteGroupResponse =
  DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
  body?: never;
  path: {
    groupId: string;
  };
  query?: never;
  url: '/event-group/{groupId}';
};

export type GetGroupResponses = {
  200: EventGroupDetailDto;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type AddMemberData = {
  body: MemberDto;
  path: {
    groupId: string;
  };
  query?: never;
  url: '/event-group/{groupId}/member';
};

export type AddMemberResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type AddMemberResponse = AddMemberResponses[keyof AddMemberResponses];

export type DeleteMemberData = {
  body?: never;
  path: {
    groupId: string;
    memberId: string;
  };
  query?: never;
  url: '/event-group/{groupId}/member/{memberId}';
};

export type DeleteMemberResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type DeleteMemberResponse =
  DeleteMemberResponses[keyof DeleteMemberResponses];

export type AddExpenseData = {
  body: ExpenseDto;
  path: {
    groupId: string;
  };
  query?: never;
  url: '/event-group/{groupId}/expense-record';
};

export type AddExpenseResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type AddExpenseResponse = AddExpenseResponses[keyof AddExpenseResponses];

export type UpdateExpenseData = {
  body: ExpenseDto;
  path: {
    groupId: string;
    expenseId: string;
  };
  query?: never;
  url: '/event-group/{groupId}/expense-record/{expenseId}';
};

export type UpdateExpenseResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type UpdateExpenseResponse =
  UpdateExpenseResponses[keyof UpdateExpenseResponses];

export type ClientOptions = {
  baseUrl: string;
};
