@baseUrl = http://localhost:3005
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWQ1ZTRkYy1lZTI0LTQ5NTgtOTQ5ZS1iODVhZGQ1Y2U5NjUiLCJpYXQiOjE3NjUyNjA5NjAsImV4cCI6MTc2NTI2MTAyMH0.NLQbd2kG9CshPkAJYDnAZ21W4_918AL8w--8k2KicIE
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWQ1ZTRkYy1lZTI0LTQ5NTgtOTQ5ZS1iODVhZGQ1Y2U5NjUiLCJpYXQiOjE3NjUyNjA5NjAsImV4cCI6MTc2NTI2Mjc2MH0.kuWUqVTcawLdUeDEyB9p8w0Ksr6pr72tPdl92cvyINQ

# ログイン
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "itakai199969@gmail.com",
  "password": "Itakura71110"
}

###

# ユーザー情報取得
GET {{baseUrl}}/user/me
Authorization: Bearer {{accessToken}}

###

# トークンリフレッシュ
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}