import { Toaster } from '@repo/ui/components';
import '@repo/ui/globals.css';
import type { Metadata } from 'next';
import { M_PLUS_2 } from 'next/font/google';

const mPlus2 = M_PLUS_2({
  weight: '400',
  variable: '--font-m-plus-2',
  subsets: ['latin-ext'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function BaseLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mPlus2.variable}  font-m-plus-2 antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
