import '@repo/ui/globals.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, M_PLUS_2 } from 'next/font/google';

const mPlus2 = M_PLUS_2({
  weight: '400',
  variable: '--font-m-plus-2',
  subsets: ['latin-ext'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mPlus2.variable} ${geistSans.variable} ${geistMono.variable} font-m-plus-2 antialiased`}
      >
        <div className="px-4">{children}</div>
      </body>
    </html>
  );
}
